services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    networks:
      - proxy_net
    # Exponemos 80 y 443 para HTTP y HTTPS
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  proxy_net:
    name: proxy_net
    driver: bridge
