# PATH: ./docker-compose.override.yml
services:
  traefik:
    container_name: traefik-dev
    # Añadimos el dashboard en el 8080 (ya estaba)
    ports:
      - "8080:8080"
    volumes:
      - ./acme.json:/acme.json
      - ./traefik.dev.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic_conf.dev.yml:/etc/traefik/dynamic_conf.dev.yml:ro

  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    container_name: whoami-container
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
      - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami-test`)"
    networks:
      - proxy_net

