entryPoints:
  http:
    address: ":80"
  traefik:
    address: ":8080"

api:
  dashboard: true
  insecure: true  # Permite acceder sin autenticaci칩n en dev (cambiar en producci칩n)

log:
  level: DEBUG  # Cambia a DEBUG para m치s informaci칩n en logs

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: "/etc/traefik/dynamic_conf.dev.yml"
    watch: true
